before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/ccexplorer
    id: all
    binary: ccexplorer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    gobinary: "go"
    goarch:
      - amd64
      - arm64
      - arm

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: cduggn
    homepage: "https://github.com/cduggn/ccExplorer"
    tap:
      owner: cduggn
      name: homebrew-cduggn
    commit_author:
      name: cduggn
      email: duggan.colin@gmail.com

dockers:
  - image_templates:
      - 'ghcr.io/cduggn/ccexplorer:{{ .Tag }}'
    dockerfile: Dockerfile-releaser
    goos: linux
    goarch: amd64


checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'